**IMPORTING BASIC LIBRARIES**

In [33]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

**READING THE DATASET**

In [34]:
df=pd.read_csv("data/CTG.csv")


**CLEANING THE DATA AND PREPARING INPUT AND OUTPUT FIELDS**

In [35]:
df=df.drop(["FileName","Date","SegFile","b","e"],axis=1)
df=df.dropna()
df.isnull().sum()
X=df[['LBE', 'LB', 'AC', 'FM', 'UC', 'DL',
       'DS', 'DP', 'DR']]
Y=df[["NSP"]]

**PERFORMING THE SCALING**

In [36]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
Scaler=StandardScaler()
X=Scaler.fit_transform(X)

**SPLITTING THE DATASET INTO TRAINING SET AND TEST SET**

In [37]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

**SUPPORT VECTOR CLASSIFIER MODEL**

In [38]:
from sklearn.svm import SVC

svm_clf=SVC(kernel="poly",degree=6,coef0=5,gamma=0.1)
svm_clf=svm_clf.fit(X_train,y_train)
y_pred=svm_clf.predict(X_test)

**CALCULATING DIFFERENT METRICS**

In [39]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix
print("CONFUSION MATRIX")
print(confusion_matrix(y_test,y_pred))
print("F1-score:",f1_score(y_test,y_pred,average='weighted'))
print("Accuracy-score:",accuracy_score(y_test,y_pred))
print("Precision-score:",precision_score(y_test,y_pred,average='weighted'))
print("Recall-score:",recall_score(y_test,y_pred,average="weighted"))

CONFUSION MATRIX
[[470  20   6]
 [ 29  62  10]
 [  8   5  28]]
F1-score: 0.8753514883881671
Accuracy-score: 0.877742946708464
Precision-score: 0.8744054575648664
Recall-score: 0.877742946708464


**SAVING THE SVM MODEL FOR FUTURE PURPOSES**

In [40]:
import joblib
joblib.dump(svm_clf, './models/svc-model')
#model=joblib.load('./models/svc-model') for loading a model

['./models/svc-model']

**DECISION TREE CLASSIFIER**

In [41]:
from sklearn.tree import DecisionTreeClassifier
tree_clf=DecisionTreeClassifier(min_samples_split=6, min_samples_leaf=4, max_depth=6, )
tree_clf=tree_clf.fit(X_train,y_train)
y_pred=tree_clf.predict(X_test)


**PRINTING THE METRICS OF DTC**

In [42]:
print("Accuracy-score:",accuracy_score(y_test,y_pred))
print("Recall-score:",recall_score(y_test,y_pred,average="weighted"))
print("Precision-score:",precision_score(y_test,y_pred,average='weighted'))

Accuracy-score: 0.8683385579937304
Recall-score: 0.8683385579937304
Precision-score: 0.8603398399877494


In [49]:
# from sklearn.tree import export_graphviz
# g=export_graphviz(
# tree_clf, out_file="tree.dot",
# feature_names=['LBE', 'LB', 'AC', 'FM', 'UC', 'DL',
#        'DS', 'DP', 'DR'],
# class_names=["NSP"],
# rounded=True,
# filled=True)
# graph = graphviz.Source(g)
# graph.render("decision_tree", format="png")
# from subprocess import check_call
# check_call(['dot','-Tpng','tree.dot','-o','tree.png'])
print(Y.shape)



(2126, 1)
